### ISSUE TITLE
[BLOCKER] msstats pdfs empty

### ISSUE THREAD

**Issue by jpfeuffer** [nf-core/quantms#42]
### Description of the bug

https://nf-co.re/quantms/results#quantms/results-6ffb0c92964cb70e212e18225c769b9e26cb1c11/mode_lfq/msstats/

**Comment by jpfeuffer** [comment]
```
nxf-scratch-dir ip-172-31-24-77.eu-west-1.compute.internal:/tmp/nxf.XXXX0NAI7V
Loading required package: MSstats
Attaching package: ‘MSstats’
The following object is masked from ‘package:grDevices’:
    savePlot
Loading required package: tibble
Loading required package: data.table
Error in .plotHeatmap(input, logBase.pvalue, ylimUp, FCcutoff, sig, clustering,  :
  At least two proteins are needed for heatmaps.
Calls: groupComparisonPlots -> .plotHeatmap
Execution halted
Optional MSstats step failed. Please check logs and re-run or do a manual statistical analysis.
Attaching package: ‘MSstats’
The following object is masked from ‘package:grDevices’:
    savePlot
```

**Comment by jpfeuffer** [comment]
```
msstats_tmt.R \
    out_msstats.csv \
    pairwise \
    "" \
    true \
    true \
    true \
    sum \
    msstats \
    true \
    true \
    true \
     \
    > msstats_tmt.log \
    || echo "Optional MSstatsTMT step failed. Please check logs and re-run or do a manual statistical analysis."
```

A tee is missing here

**Comment by daichengxin** [comment]
Because most of the features are filtered by msstats, the final result is only one protein. And the pvalue is a null value. Can't draw a comparison chart. Maybe the msstats step should be skipped in test_lfq? DIA test data can be analyzed normally for msstats

Protein | Label | log2FC | SE | Tvalue | DF | pvalue | adj.pvalue | issue | MissingPercentage | ImputationPercentage | 1 | 2 | 3
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
P02769\|ALBU_BOVIN | 1-2 | 0.782279338943049 | NA | NA | 0 | NA | NA | NA | 0 | 0 | 0 | 0 | 0
P02769\|ALBU_BOVIN | 1-3 | 0.522695033225762 | NA | NA | 0 | NA | NA | NA | 0 | 0 | 0 | 0 | 0
P02769\|ALBU_BOVIN | 2-3 | -0.259584305717286 | NA | NA | 0 | NA | NA | NA | 0 | 0 | 0 | 0 | 0

**Comment by jpfeuffer** [comment]
Ok. What about TMT?

I think it would be nice if MSstats can run through without the plots. Because sometimes you just want the normalization and imputation. Even if you don't have different conditions or very few proteins.

Maybe we should not produce an empty pdf. Maybe use a try catch and delete the pdf if the function did not work. Or check if all proteins have "null" pvalues.

Maybe also add a nextflow warning since the warnings inside R are not easily visible?

**Comment by daichengxin** [comment]
Fixed https://github.com/bigbio/quantms/pull/179
